
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.VBox vbox1;
	private global::Gtk.HBox hbox2;
	private global::Gtk.VBox vbox2;
	private global::Gtk.Table table2;
	private global::Gtk.Entry entryAgility;
	private global::Gtk.Entry entryCharisma;
	private global::Gtk.Entry entryEndurance;
	private global::Gtk.Entry entryIntelligence;
	private global::Gtk.Entry entryName;
	private global::Gtk.Entry entryStrength;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView textview3;
	private global::Gtk.Label label10;
	private global::Gtk.Label label11;
	private global::Gtk.Label label5;
	private global::Gtk.Label label6;
	private global::Gtk.Label label7;
	private global::Gtk.Label label8;
	private global::Gtk.Label label9;
	private global::Gtk.ComboBoxEntry comboboxentry2;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Button button1;
	private global::Gtk.HBox hbox4;
	private global::Gtk.ToggleButton togglebutton1;
	private global::Gtk.ToggleButton togglebutton2;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.HeightRequest = 50;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Race Creation");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.table2 = new global::Gtk.Table (((uint)(7)), ((uint)(2)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.entryAgility = new global::Gtk.Entry ();
		this.entryAgility.CanFocus = true;
		this.entryAgility.Name = "entryAgility";
		this.entryAgility.IsEditable = true;
		this.entryAgility.InvisibleChar = '●';
		this.table2.Add (this.entryAgility);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2 [this.entryAgility]));
		w2.TopAttach = ((uint)(2));
		w2.BottomAttach = ((uint)(3));
		w2.LeftAttach = ((uint)(1));
		w2.RightAttach = ((uint)(2));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.entryCharisma = new global::Gtk.Entry ();
		this.entryCharisma.CanFocus = true;
		this.entryCharisma.Name = "entryCharisma";
		this.entryCharisma.IsEditable = true;
		this.entryCharisma.InvisibleChar = '●';
		this.table2.Add (this.entryCharisma);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.entryCharisma]));
		w3.TopAttach = ((uint)(5));
		w3.BottomAttach = ((uint)(6));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(2));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.entryEndurance = new global::Gtk.Entry ();
		this.entryEndurance.CanFocus = true;
		this.entryEndurance.Name = "entryEndurance";
		this.entryEndurance.IsEditable = true;
		this.entryEndurance.InvisibleChar = '●';
		this.table2.Add (this.entryEndurance);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.entryEndurance]));
		w4.TopAttach = ((uint)(3));
		w4.BottomAttach = ((uint)(4));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.entryIntelligence = new global::Gtk.Entry ();
		this.entryIntelligence.CanFocus = true;
		this.entryIntelligence.Name = "entryIntelligence";
		this.entryIntelligence.IsEditable = true;
		this.entryIntelligence.InvisibleChar = '●';
		this.table2.Add (this.entryIntelligence);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2 [this.entryIntelligence]));
		w5.TopAttach = ((uint)(4));
		w5.BottomAttach = ((uint)(5));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.entryName = new global::Gtk.Entry ();
		this.entryName.CanFocus = true;
		this.entryName.Name = "entryName";
		this.entryName.IsEditable = true;
		this.entryName.InvisibleChar = '●';
		this.table2.Add (this.entryName);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2 [this.entryName]));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.entryStrength = new global::Gtk.Entry ();
		this.entryStrength.CanFocus = true;
		this.entryStrength.Name = "entryStrength";
		this.entryStrength.IsEditable = true;
		this.entryStrength.InvisibleChar = '●';
		this.table2.Add (this.entryStrength);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2 [this.entryStrength]));
		w7.TopAttach = ((uint)(1));
		w7.BottomAttach = ((uint)(2));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview3 = new global::Gtk.TextView ();
		this.textview3.CanFocus = true;
		this.textview3.Name = "textview3";
		this.GtkScrolledWindow.Add (this.textview3);
		this.table2.Add (this.GtkScrolledWindow);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2 [this.GtkScrolledWindow]));
		w9.TopAttach = ((uint)(6));
		w9.BottomAttach = ((uint)(7));
		w9.LeftAttach = ((uint)(1));
		w9.RightAttach = ((uint)(2));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Base Charisma");
		this.table2.Add (this.label10);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2 [this.label10]));
		w10.TopAttach = ((uint)(5));
		w10.BottomAttach = ((uint)(6));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.Yalign = 0.1F;
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Description");
		this.table2.Add (this.label11);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2 [this.label11]));
		w11.TopAttach = ((uint)(6));
		w11.BottomAttach = ((uint)(7));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Race Name");
		this.table2.Add (this.label5);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2 [this.label5]));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Base Strength");
		this.table2.Add (this.label6);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table2 [this.label6]));
		w13.TopAttach = ((uint)(1));
		w13.BottomAttach = ((uint)(2));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Base Agility");
		this.table2.Add (this.label7);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2 [this.label7]));
		w14.TopAttach = ((uint)(2));
		w14.BottomAttach = ((uint)(3));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Base Endurance");
		this.table2.Add (this.label8);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table2 [this.label8]));
		w15.TopAttach = ((uint)(3));
		w15.BottomAttach = ((uint)(4));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Base Intelligence");
		this.table2.Add (this.label9);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table2 [this.label9]));
		w16.TopAttach = ((uint)(4));
		w16.BottomAttach = ((uint)(5));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox2.Add (this.table2);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table2]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		this.hbox2.Add (this.vbox2);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox2]));
		w18.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.comboboxentry2 = global::Gtk.ComboBoxEntry.NewText ();
		this.comboboxentry2.WidthRequest = 130;
		this.comboboxentry2.Name = "comboboxentry2";
		this.hbox2.Add (this.comboboxentry2);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.comboboxentry2]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Add Race");
		this.hbox1.Add (this.button1);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button1]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.togglebutton1 = new global::Gtk.ToggleButton ();
		this.togglebutton1.CanFocus = true;
		this.togglebutton1.Name = "togglebutton1";
		this.togglebutton1.UseUnderline = true;
		this.togglebutton1.Label = global::Mono.Unix.Catalog.GetString ("Save Changes");
		this.hbox4.Add (this.togglebutton1);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.togglebutton1]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.togglebutton2 = new global::Gtk.ToggleButton ();
		this.togglebutton2.CanFocus = true;
		this.togglebutton2.Name = "togglebutton2";
		this.togglebutton2.UseUnderline = true;
		this.togglebutton2.Label = global::Mono.Unix.Catalog.GetString ("Write Race Definition File");
		this.hbox4.Add (this.togglebutton2);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.togglebutton2]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		this.hbox1.Add (this.hbox4);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbox4]));
		w24.Position = 1;
		w24.Expand = false;
		w24.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w25.Position = 1;
		w25.Expand = false;
		w25.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 482;
		this.DefaultHeight = 330;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
